# Generated by Django 4.2.5 on 2023-10-18 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manon_app', '0002_blog_emailstore_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='title1',
        ),
    ]
