# Generated by Django 4.2.5 on 2023-10-18 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manon_app', '0003_rename_title_blog_title1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='BlogData',
        ),
    ]
