# Generated by Django 4.2.5 on 2023-10-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manon_app', '0004_rename_blog_blogdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
