# Generated by Django 4.2.5 on 2023-12-04 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manon_app', '0005_image_image1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image1',
        ),
        migrations.CreateModel(
            name='OtpStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=4)),
                ('vrify', models.BooleanField(default=False)),
                ('cr_date', models.DateTimeField(auto_now=True)),
                ('otp_count', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
