# Generated by Django 4.2.8 on 2023-12-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manon_app', '0007_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='p_image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
