# Generated by Django 4.2.8 on 2023-12-12 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manon_app', '0009_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_image', to='manon_app.blogdata'),
        ),
    ]
