# Generated by Django 4.2.8 on 2023-12-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manon_app', '0011_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
