# Generated by Django 4.2.8 on 2023-12-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manon_app', '0012_userprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdata',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='design',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
