# Generated by Django 4.2.8 on 2023-12-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manon_app', '0013_blogdata_time_design_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdata',
            name='time',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
