# Generated by Django 4.2.8 on 2023-12-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manon_app', '0014_alter_blogdata_time_alter_design_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdata',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
