# Generated by Django 4.2.8 on 2023-12-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manon_app', '0015_blogdata_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdata',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
