# Generated by Django 4.2.8 on 2023-12-24 12:04

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manon_app', '0017_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdata',
            name='blog_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title1', unique=True),
        ),
    ]
