# Generated by Django 4.2.8 on 2023-12-25 06:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manon_app', '0018_blogdata_blog_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='LikeData',
        ),
    ]
