# Generated by Django 4.2.8 on 2023-12-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manon_app', '0019_rename_like_likedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdata',
            name='comment',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='blogdata',
            name='like',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
