# Generated by Django 4.2.8 on 2023-12-30 09:45

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manon_app', '0022_replydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='blog_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='ditels', unique=True),
        ),
    ]
