# Generated by Django 4.2.8 on 2023-12-30 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manon_app', '0023_design_blog_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='blog_slug',
            new_name='image_slug',
        ),
    ]
