# Generated by Django 4.2.8 on 2024-02-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manon_app', '0024_rename_blog_slug_design_image_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
