# Generated by Django 4.2.8 on 2024-02-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manon_app', '0025_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
