# Generated by Django 4.2.8 on 2024-02-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manon_app', '0026_alter_subscribe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='design_like',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='design_view',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
