# Generated by Django 4.2.8 on 2024-02-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manon_app', '0028_alter_design_design_like_alter_design_design_view_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdata',
            name='blog_view',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
