# Generated by Django 4.2.8 on 2024-02-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manon_app', '0029_blogdata_blog_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdata',
            name='time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
