# Generated by Django 4.2.8 on 2024-02-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manon_app', '0030_alter_blogdata_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentdata',
            name='com_status',
            field=models.CharField(blank=True, choices=[('published', 'published'), ('review', 'review')], default='review', max_length=10, null=True),
        ),
    ]
