# Generated by Django 4.2.8 on 2024-02-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manon_app', '0031_commentdata_com_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentdata',
            name='com_status',
            field=models.CharField(blank=True, choices=[('published', 'published'), ('review', 'review')], default='Under Review', max_length=10, null=True),
        ),
    ]
