# Generated by Django 4.2.8 on 2024-02-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manon_app', '0032_alter_commentdata_com_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentdata',
            name='com_status',
            field=models.CharField(blank=True, choices=[('Published', 'Published'), ('Under Review', 'Under Review')], default='Under Review', max_length=20, null=True),
        ),
    ]
