# Generated by Django 4.2.8 on 2024-02-13 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manon_app', '0033_alter_commentdata_com_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentdata',
            old_name='com_status',
            new_name='comm_status',
        ),
    ]
