# Generated by Django 4.2.8 on 2024-02-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manon_app', '0034_rename_com_status_commentdata_comm_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='design_like1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='design_view1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
