# Generated by Django 4.2.8 on 2024-02-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manon_app', '0035_design_design_like1_design_design_view1'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdata',
            name='blog_tag',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='design_tag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
