# Generated by Django 4.2.8 on 2024-02-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manon_app', '0036_blogdata_blog_tag_design_design_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='img_alt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='img_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
